---
- name: Install cronie
  pacman:
    name: cronie
    state: present

- name: Set User/Group owner and permission on /etc/cron.*
  file:
    path: "{{ item }}"
    state: directory
    mode: og-rwx
  with_items:
    - "/etc/cron.d"
    - "/etc/cron.hourly"
    - "/etc/cron.daily"
    - "/etc/cron.weekly"
    - "/etc/cron.monthly"

- name: Restrict at/cron to Authorized Users (Remove {at,cron}.deny)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/at.deny"
    - "/etc/cron.deny"

- name: Restrict at to Authorized Users ({at,cron}.allow)
  file:
    path: "{{ item }}"
    state: touch
    mode: og-rwx
    owner: root
    group: root
  with_items:
    - "/etc/at.allow"
    - "/etc/cron.allow"