---
- debug:
    msg: "{{ vars[(role_path | basename).split('.')[-1].replace('-','_')] }}"
  when: DEBUG | d() | bool

- include_tasks: hostname.yml
- include_tasks: configure.yml
- include_tasks: sysctl.yml
- include_tasks: ufw.yml
- include_tasks: limits.yml
- include_tasks: login.defs.yml
- include_tasks: rhosts.yml
- include_tasks: securetty.yml
- include_tasks: suid_sgid.yml
- include_tasks: cron.yml
- include_tasks: banner.yml
- include_tasks: ntp.yml
- include_tasks: sshd.yml
- include_tasks: clamav.yml
  when: ansible_arch_system.clamav.enabled
