---
- name: Change various sysctl-settings, look at the sysctl-vars file for documentation
  sysctl:
    sysctl_file: "/etc/sysctl.d/50-ansible.conf"
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    - "{{ ansible_arch_system.sysctl }}"
  notify:
    - "reload sysctl.conf"

#- name: Protect sysctl.conf
#  file:
#    path: '/etc/sysctl.d/ansible.conf'
#    owner: 'root'
#    group: 'root'
#    mode: '0440'
#    state: touch
